import Head from 'next/head'
import Footer from '../components/Footer'
import Header from '../components/Header'
import styles from '../styles/Passageiros.module.css'
import { api } from '../service/api';
import { useEffect, useState } from 'react';
import TablePassageiro from '../components/TablePassageiro';

export default function Passageiros() {

    const [passageiros, setPassageiros] = useState<any[]>([])
    const [alterPassageiro, setAlterPassageiro] = useState(0)

    const columns = [
        'CPF',
        'Nome',
        'Sexo',
        'RG',
        'Data de Nascimento',
    ];


    useEffect(() => {
        api.get('passageiros').then((response) => {
            setPassageiros(response.data);
        })
    }, [alterPassageiro]);

    return (
        <div className={styles.container}>
            <Head>
                <title>Vooe - Sistema de Gerenciamento</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header title="Passageiros"/>
            <div className={styles.content}>
                <TablePassageiro 
                    columns={columns} 
                    data={passageiros} 
                    setAlterPassageiro={setAlterPassageiro}
                    alterPassageiro={alterPassageiro}
                />
            </div>
            <Footer/>
        </div>
    )
}