import Head from 'next/head'
import Footer from '../components/Fotter'
import Header from '../components/Header'
import styles from '../styles/Passageiros.module.css'

export default function Passageiros() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Vooe - Sistema de Gerenciamento</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.content}>

            </div>
            <Footer/>
            <Header title="Passageiros"/>
        </div>
    )
}